version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: credit_card_api
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
